### ISSUE TITLE
OSD file stop recording when goggle dvr record over 10 min

### ISSUE THREAD

**Issue by Taical** [bri3d/msp-osd#105]
I enable OSD file recording and it work, but if I record dvr over 10 min, the Dji goggle will create a new mp4 file to keep recording because it is maximum 10 min per mp4 file, but the OSD file will not automatically keep recording over 10 min.

**Comment by Knifa** [comment]
The recording doesn't roll over at the minute, but it's something to be dealt with. 😄 

If you disable loop recording mode, the goggles will produce continuous videos instead and the OSD recorder will too. Obviously, you need to clear out files yourself because of this, but it's the best workaround at the moment.

**Comment by Taical** [comment]
I got it ! thanks for your help!
