### ISSUE TITLE
msp OSD is not working on Nebula Pro Air Unit

### ISSUE THREAD

**Issue by derpolygraf** [bri3d/msp-osd#110]
I have the following problem, my Nebula Pro Air Unit shows no msp OSD. My Setup is a Speedybee F7 V3 with BF 4.4. I have done all the things on https://github.com/fpv-wtf/msp-osd#flight-controller-setup. The standard OSD works perfectly (see photo). That is why I think that the diodes for TX and RX on the unit cannot be broken ( As in the case: https://www.youtube.com/watch?v=0UjG1ki1hJM). 

The msp OSD works on my old DJI Air Unit with my DJI goggles V1 on a Kakute F7 HDV.

What could be the problem here? Please help!

![WhatsApp Bild 2023-04-01 um 12 08 04](https://user-images.githubusercontent.com/91729981/229281842-d7d411e5-84a9-4f7c-99dd-2528cb5875a4.jpg)

**Comment by j005u** [comment]
Did you remember to also root and install msp-osd on the second vista?

Since you can see the DJI custom OSD then the UART must be physically fine indeed.

The other reason I can think this might happen is maybe you selected the wrong UART on the BF side for the Display Port peripheral. DJI's custom OSD would still work as it works by fetching telemetry from the FC using just the MSP standard.

**Comment by derpolygraf** [comment]
> 
I found the problem, I did not update  WTFOS in the dji google. Now it works
