### ISSUE TITLE
Support for video link signal strength on OSD

### ISSUE THREAD

**Issue by fabriciopolonio** [bri3d/msp-osd#17]
Is it possible to show the VTX link strength when using MSP OSD mode?

**Comment by bri3d** [comment]
Not yet, it’s a feature I’d like to add when I get a chance

**Comment by druckgott** [comment]
Are there any news, this is for me the most important point I did not switch to your total cool osd, because I always want to have the mbit and the latence (more important the mbit), because this gives me the best indication how good the signal is and when I should return due to the bad signal.
If this is implemented I will directly switch ;-) so I really waiting for this.

**Comment by bri3d** [comment]
mbit and latency have been implemented. there are other strength metrics we could try to use in the future, but I think this is resolved
