### ISSUE TITLE
F722 betaflight 4.3.1 - SERIAL CPU headache

### ISSUE THREAD

**Issue by master0id** [bri3d/msp-osd#35]
I've activated MSP OSD, on STM32F722 FC, everything is working, but in flight - I got some prephireal devices dissapear - for example GPS, it's just disappeared and not seen in configurator. 1st I think GPS was damaged, but when I did some investigation at home - F722 CPU is heating like hell... And as you can see on screenshot - with "tasks" command - it got 3887% CPU usage for SERIAL.... it seems there is a bug somewhere in code.. 

<img width="722" alt="Screenshot 2022-08-26 at 20 26 28" src="https://user-images.githubusercontent.com/79976003/186960700-3843660c-9cb0-46ef-815f-2d86feb4e354.png">

**Comment by bri3d** [comment]
My understanding is that the CPU reporting for the SERIAL task in Betaflight may not be accurate, which is why the totals exclude SERIAL. 

msp-osd does not send any MSP messages above and beyond those which the DJI software sends by default. The combination of MSP DisplayPort and the inbound MSP messages from DJI may be challenging for your FC for some reason, but I have never seen this before using hardware serial.

Turning off the DJI Custom OSD if you have not done so already will reduce the serial traffic by a little.

Regardless, this is an issue either with hardware somehow or for Betaflight, not with msp-osd.
