### ISSUE TITLE
I see double (OSD items).

### ISSUE THREAD

**Issue by AndKe** [bri3d/msp-osd#40]
I've used DJI's BetaFlight OSD support - now installed msp-osd.
When I configure any item that is supported by both OSD's, like satcount, altitude, RSSI - then I see those elements both in the blocky Betaflight OSD design   - and DJI design , with an offset.

How can I make only one of those display the items that are supported by both?

I've read README.md and "Additional Reading / Learning"  - finding nothing on the topic.

**Comment by j005u** [comment]
You can't at the moment, they rely on the same OSD config from the FC.

MSP-OSD should support *all* elements, so for now the fix is to just turn off DJI's custom OSD option.

Due to how things are set up right now, it's non-trivial to add this functionality in a maintainable way, even though it doesn't seem so on the surface level.

**Comment by AndKe** [comment]
Ah! - of course! - I mistakingly thought of the "custom OSD" setting to now apply to MSP-OSD :)

**Comment by AndKe** [comment]
thank you for this great software.
